apiVersion: v1
kind: Service
metadata:
  name: ${JOB_BASE_NAME}
  namespace: ${KubeNameSpace}
  labels:
    name: ${JOB_BASE_NAME}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: ${JOB_BASE_NAME}
      nodePort: ${NodePort}
      port: ${ClusterPort}
      protocol: TCP
      targetPort: ${ContainerPort}
  selector:
    app: ${JOB_BASE_NAME}
    version: ${Version}
  sessionAffinity: None
